### ISSUE TITLE
[Bug]: Non `node_local` ephemeral pod storage does not get accounted for correctly 

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#122] opened 2024-08-26 23:53 UTC
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

I was attempting to deploy a workload for local dev that builds using a `/tmp` directory, however the pods kept crashing or finding their way into `Unknown` state. My `tmp_directories` were all using the default of `node_local` false, however on pod start up I saw the below:

![image](https://github.com/user-attachments/assets/0c8b7420-d9b4-4d1a-9fff-5932d40e3c66)

Looking at the `kube_pod` module it does not add the non-`node_local` storage to its `ephemeral-storage` limit on the container spec, and it seems like when you use past that limit, even without a mounted volume, the container crashes

### Steps to Reproduce

1. Create a workload with a non-`node_local` `tmp_directory` with capacity greater than that of `node_local` `tmp_directories` + `100Mi` (the default overhead over the `node_local` storage
2. Use the entirety of the non-`node_local` `tmp_directory`
3. Observe your container bomb

**Comment by fullykubed** [comment] 2024-08-27 03:34
Can you provide an example pod manifest where this problem occurs?

**Comment by fullykubed** [comment] 2024-08-27 12:17
@jlevydev I believe we need to look into the particulars of your setup as I am unable to reproduce.

I have created an instance of kube_deployment with the following temporary directory:

```hcl
  tmp_directories = {
    "tmp" = {
      mount_path = "/tmp"
      node_local = false
      size_mb = 1024
    }
  }
```

The resulting pod has the following resource config:

```yaml
    resources:
      limits:
        ephemeral-storage: 100Mi
        memory: "136314880"
      requests:
        cpu: 10m
        ephemeral-storage: 100Mi
        memory: "104857600"
```

I am then able to write a 1GB file to the `/tmp` directory (`dd if=/dev/zero of=/tmp/test bs=1M count=1024`) successfully and without disruption.

This aligns with the Kubernetes specification as described [here](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-emphemeralstorage-consumption) which explicitly lists what is controlled by the `ephemeral-storage` limits / requests. Mounted PVCs (created when `node_local = false`) are not included in that limit; this makes sense b/c `ephemeral-storage` is meant to allocate resources provided directly by the node and PVCs are not node-scoped.

There are a couple possibilities for what you may be experiencing:

1. You have not set `readonly` to `true` and are actually writing files outside of your temporary directories. This creates a "writeable container layer" and the size of this layer _is_ applied against the  `ephemeral-storage` limit.

2. You may have a runaway process that is writing a huge amount of logs and this is overwhelming the node's abilities to process and rotate the log files. As on-disk log size is also counted against the `ephemeral-storage` limit, this could also result in the problem you are seeing.

**Comment by fullykubed** [comment] 2024-08-27 14:17
I am a little confused as in that example you have `node_local` set to` true`? In the original post, you were referencing issues with temporary directories with `node_local` set to `false` (non-`node_local`).

**Comment by jlevydev** [comment] 2024-08-27 14:19
Sorry, that's my current deployment, the one causing issues was the same except with `node_local` unset since it's optional in the object

**Comment by fullykubed** [comment] 2024-08-29 16:08
@jlevydev I am going to close this issue as given our attempts to reproduce I do not think this is a bug in the stack.

Feel free to re-open / continue commenting here if you find any additional information that would indicate otherwise.

**Closed by fullykubed** 2024-08-29 16:08 UTC
Labels: bug, enterprise customer
