### ISSUE TITLE
[Bug]: `common_env` on `wf_spec` is not common if other environment variables are set in the `template`

### ISSUE THREAD

**Issue by jlevydev** [Panfactum/stack#134] opened 2024-09-11 21:11 UTC
### Prior Search

- [X] I have already searched this [project's issues](https://github.com/Panfactum/stack/issues) to determine if a bug report has already been made.

### What happened?

When attempting to define a workflow I have a common environment and  a container I'd like to inherit that environment plus some custom environment variables I set directly in the `container` spec of the template. My assumption was that these two environments would be merged, but it actually only gets the custom environment variables I set. 

When looking at the code it seems that `common_env` is used in the `container_defaults` section which I think is potentially the issue given the moment you define an `env` on the `container` spec you no longer gain the defaults. 

### Steps to Reproduce

1. Define a `wf_spec`
2. Set `common_env` to some set of values
3. Set `env` on a `container` spec in `templates` to a distinct set of values from `common_env`
4. Observe the resulting WorkFlow spec only have the values set in `3`

**Comment by fullykubed** [comment] 2024-09-12 01:39
Good question!

This is by design as if they were merged there would be no way to drop the default configurations for any container.

You can read more about this design decision in our documentation [here](https://panfactum.com/docs/edge/reference/infrastructure-modules/submodule/workflow/wf_spec#overriding-the-template-defaults).

The `wf_spec` module contains a `env` output that can be used to merge in additional environment variables on a per-container basis per the documentation linked above.

**Closed by fullykubed** 2024-09-12 01:39 UTC
Labels: bug
